### ISSUE TITLE
[BUG] Gctf download link in the wiki is not working anymore

### ISSUE THREAD

**Issue by n1kt0** [KudryashevLab/TomoBEAR#19]
The  Gctf download link in the wiki is not working anymore.
Following link seems to be a working one:
https://www2.mrc-lmb.cam.ac.uk/download/gctf_v1-06-and-examples/
Next link seems also to work for a cuda updated version:
https://www2.mrc-lmb.cam.ac.uk/download/gctf_gautomatch_cu10-1-tar-gz/

**Comment by ArtsemiY** [comment]
fixed in _develop_ 
changes in wiki will appear with the next release

**Comment by ArtsemiY** [comment]
updated wiki during the latest release (v0.3.0)
