### ISSUE TITLE
[BUG?] pipeline crashes at parfoor loop

### ISSUE THREAD

**Issue by rickhooy** [KudryashevLab/TomoBEAR#23]
**Describe the bug**

While executing Ribosome tutorial and test dataset matlab errors out at parfor loop. For each project the pipeline crashes at distinct steps - see Screenshots

**Test Project JSON file**

```JSON
{
    "general": {
        "project_name": "test",
        "project_description": "Practice test",
        "data_path": "/data/tb/Frames/*.tif",
        "processing_path": "/data/tb/processing",
        "expected_symmetrie": "C1",
        "template_matching_binning": 8,
        "gold_bead_size_in_nm": 10,
        "reconstruction_thickness": 3000,
        "rotation_tilt_axis": 79,
        "aligned_stack_binning": 2,
        "pre_aligned_stack_binning": 2,
        "binnings": [2, 4, 8]
    },
    "MetaData": {
    },
    "SortFiles": {
    },
    "MotionCor2": {
    },
    "CreateStacks": {
    },
    "DynamoTiltSeriesAlignment": {
    },
    "DynamoCleanStacks": {
    },
    "BatchRunTomo": {
        "skip_steps": [4],
        "ending_step": 6
    },
    "StopPipeline": {
    },
    "BatchRunTomo": {
        "starting_step": 8,
        "ending_step": 8
    },
    "GCTFCtfphaseflipCTFCorrection": {
    },
    "BatchRunTomo": {
        "starting_step": 10,
        "ending_step": 13
    },
    "BinStacks": {
    },
    "Reconstruct": {
        "reconstruct": "binned"
    },
    "DynamoImportTomograms": {
    },
    "EMDTemplateGeneration": {
        "template_emd_number": "4015"
    },
    "DynamoTemplateMatching": {
        "sampling": 15
    },
    "TemplateMatchingPostProcessing": {
        "parallel_execution": false,
        "cc_std": 2.5,
        "crop_particles": true,
        "as_boxes": true,
        "box_size": 1.5
    },
    "DynamoAlignmentProject": {
        "iterations": 3,
        "classes": 4,
        "use_symmetrie": false,
        "use_noise_classes": true
    },
    "DynamoAlignmentProject": {
        "iterations": 3,
        "classes": 4,
        "use_noise_classes": true,
        "use_symmetrie": false,
        "selected_classes": [1]
    },
    "DynamoAlignmentProject": {
        "iterations": 3,
        "classes": 4,
        "use_noise_classes": true,
        "use_symmetrie": false,
        "selected_classes": [1]
    },
    "BinStacks": {
        "use_ctf_corrected_aligned_stack": false,
        "binnings": [2, 4, 8]
    },
    "DynamoAlignmentProject": {
        "iterations": 3,
        "classes": 4,
        "use_noise_classes": true,
        "use_symmetrie": true,
        "selected_classes": [1],
        "binning": 8
    },
    "StopPipeline": {
    },
    "DynamoAlignmentProject": {
        "classes": 1,
        "iterations": 1,
        "use_noise_classes": false,
        "swap_particles": false,
        "use_symmetrie": true,
        "cone_flip": 1,
        "selected_classes": [1,2,3,4],
        "box_size": 0.666,
        "binning": 4,
        "threshold": 0.9
    },
    "DynamoAlignmentProject": {
        "classes": 1,
        "iterations": 1,
        "use_noise_classes": false,
        "swap_particles": false,
        "use_symmetrie": true,
        "selected_classes": [1,2],
        "binning": 2,
        "threshold": 1
    }
}
```

**Error message**

Error using BinStacks/process
Too many input arguments.

Error in iteration (line 53)
    instantiated_class = instantiated_class.process();

Error in LocalPipeline/execution_parallel (line 560)
            parfor j = 1:length(indices)

Error in LocalPipeline/execute (line 400)
                            [dynamic_configuration_out, tomogram_status{i - 1}] = obj.("execution_" + execution_method)(merged_configuration, obj.pipeline_definition{i}, previous_tomogram_status);

Error in runPipeline (line 150)
            pipeline.execute(starting_tomogram, ending_tomogram, step, gpu);

Error in runTomoBear (line 34)
runPipeline(compute_environment, configuration_path, default_configuration_path, starting_tomogram, ending_tomogram, step, gpu);
 
560             parfor j = 1:length(indices) 

**To Reproduce**
1. modified defaults.json for in-house workstation and unmodified tutorial project json
2. runTomoBear in matlab; 
runTomoBear("local","/data/tomobearTutorial/ribosome_empiar_10064_dynamo.json")
OR
runTomoBear("local","/data/tb/test.json")

**Expected behavior**
Quick search on mathworks forums did not immediately reveal reason for error

**Screenshots**
Step 26: BinStacks from Ribosome Tutorial
![tomoBear_parfor_error_ribosome](https://github.com/KudryashevLab/TomoBEAR/assets/63319417/5fe63efd-bd42-43fb-9d0d-35ef6c04ceca)

Step 6: DynamoCleanStacks from test dataset
![tomoBear_parfor_error](https://github.com/KudryashevLab/TomoBEAR/assets/63319417/6664402f-788b-4aa7-85dd-3af0cd34bbc7)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - OS Version [e.g. 22]: 20.04
 - MotionCor2 Version:  v2
 - Gctf Version: v.1.18
 - Dynamo Version: 1.1.532

**Additional context**
Could just be a default or project variable that needs to change. Please advise.

**Comment by ArtsemiY** [comment]
Hi @rickhooy ! Please, add a parameter `"execution_method": "sequential"` in the configuration sections of the problematic steps `"BinStacks"` and `"DynamoCleanStacks"` for the corresponding datasets, e.g.:
```JSON
"BinStacks": {
       "execution_method": "sequential"
}
```
and post the new error messages. 

P.S. For parallel routines there is no debug mode so that the only way to get the real error message is to switch to sequential processing mode.

**Comment by ArtsemiY** [comment]
Hey @rickhooy , thanks for sharing, glad that you resolved that one as well!

P.S. Step folders could be repeated several times, that's acceptable. The only thing which you need to keep in mind, as you already figured out, is to have step folders structure which corresponds to the input json file structure in terms of the sequence and names of the steps.

P.P.S. Additional hint for troubleshooting is to keep the structure of the ```scratch/```  folder as in input json file as well (if you experience any issues, just delete there folders made by errors or from previous runs).

I guess, the issue can be closed. Please, reopen if needed
